name = "r2-explorerrrrr"
compatibility_date = "2024-11-06"
main = "src/index.ts"
assets = { directory = "node_modules/r2-explorerrrrr/dashboard", binding = "ASSETS", html_handling = "auto-trailing-slash", not_found_handling = "single-page-application" }

# Bind R2 Buckets to your application.
# Docs: https://r2explorer.dev/getting-started/add-r2-r2-explorer-r2-buckets/
[[r2_r2-explorer-r2-buckets]]
binding = "BUCKET"
r2-explorer-r2-bucket_name = "r2-explorer-r2-bucket"
